version: '3.8'

services:
  dash-app:
    build: .
    container_name: dash_app
    restart: unless-stopped
    expose:
      - "8050"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8050/"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - dash-network

  nginx:
    image: nginx:latest
    container_name: dash_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      dash-app:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - dash-network

networks:
  dash-network:
    driver: bridge