version: '3.8'

services:
  dash-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: qml-playground:local-test
    container_name: dash_app_build_test
    restart: unless-stopped
    expose:
      - "8050"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8050/qml-playground/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - dash-build-test-network

  nginx:
    image: nginx:alpine
    container_name: dash_nginx_build_test
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      dash-app:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - dash-build-test-network

networks:
  dash-build-test-network:
    driver: bridge
